export { default as Navbar } from "./navbar/Navbar";
export { default as Brand } from "./brand/Brand";
export { default as Article } from "./howitworks/howcom";
export { default as CTA } from "./cta/CTA";
export { default as Feature } from "./feature/Feature";
export { default as Banner } from "./banner/Banner";
export { default as Info } from "./info/Info";
export { default as Contfan } from "./contact-fannuun/contfan";
export { default as Box } from "./box/box"
